### ISSUE TITLE
Can't transform *gz files to postgresql

### ISSUE THREAD

**Issue by Merzouk-Ilyes** [gregrahn/join-order-benchmark#15]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/imdbpy2sql.py", line 505, in <module>
    conn = setConnection(URI, DB_TABLES)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/imdb/parser/sql/alchemyadapter.py", line 455, in setConnection
    engine = create_engine(uri, **params)
  File "<string>", line 2, in create_engine
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 693, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'encoding' sent to create_engine(), using configuration PGDialect_psycopg2/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by Merzouk-Ilyes** [comment]
I'm trying to load the *gz files to postgresql database but i'm getting this error which is related to encoding !

**Comment by Bouncner** [comment]
Related? https://github.com/gregrahn/join-order-benchmark/issues/14

**Comment by Merzouk-Ilyes** [comment]
@Bouncner no i have a problem in the last step ( although this issue #14  still exists but i got the imdbpy2sql.py somewhere else) , the problem is in loading the GZ files to postgresql DB.
